spring:
  application:
    name: car-rental
  datasource:
    url: jdbc:mysql://localhost:3306/ucsdb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ucucs
    password: gebob123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9

server:
  port: 8080

logging:
  level:
    root: info

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ucucs.rental.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true